### replace "project-id-here" with your actual project for each of the three targets.
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: web-app
description: web-app delivery pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging
   profiles:
   - staging
 - targetId: prod
   profiles:
   - prod
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/dario-learning/locations/us-central1/clusters/testcluster
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/dario-learning/locations/us-central1/clusters/stagingcluster
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/dario-learning/locations/us-central1/clusters/prodcluster
